### ISSUE TITLE
ImportError: cannot import name 'TrackedFake' from partially initialized module 'torch._dynamo.variables.builder' (most likely due to a circular import)

### ISSUE THREAD

**Issue by yoheiueda** [torch-spyre/torch-spyre#255]
### What happened?

After upgrading to 546c59d7bbd2a08a5d2ce41b73c059d8e175e24b (#250), Running `python test_ops.py` causes  the following error.

```
  File "/home/yohei/dt-inductor/pytorch/torch/_export/non_strict_utils.py", line 17, in <module>
    from torch._dynamo.variables.builder import TrackedFake
ImportError: cannot import name 'TrackedFake' from partially initialized module 'torch._dynamo.variables.builder' (most likely due to a circular import) (/home/yohei/dt-inductor/pytorch/torch/_dynamo/variables/builder.py)
```

### What did you expect to happen?

No error

### How can we reproduce it?

```
cd torch-spyre/tests
python test_ops.py
```

### Any environmental details we need to know?

546c59d7bbd2a08a5d2ce41b73c059d8e175e24b

### Relevant log output

```Shell
Traceback (most recent call last):
  File "/home/yohei/dt-inductor/torch-spyre/tests/test_ops.py", line 22, in <module>
    from torch.testing._internal.common_utils import run_tests, TestCase
  File "/home/yohei/dt-inductor/pytorch/torch/testing/_internal/common_utils.py", line 71, in <module>
    from torch._dynamo.trace_rules import _as_posix_path
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/__init__.py", line 13, in <module>
    from . import config, convert_frame, eval_frame, resume_execution
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/convert_frame.py", line 52, in <module>
    from torch._dynamo.symbolic_convert import TensorifyState
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/symbolic_convert.py", line 57, in <module>
    from . import (
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/trace_rules.py", line 32, in <module>
    from .variables import (
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/variables/__init__.py", line 19, in <module>
    from .base import VariableTracker
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/variables/base.py", line 581, in <module>
    from . import builder
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/variables/builder.py", line 86, in <module>
    from ..side_effects import SideEffects
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/side_effects.py", line 21, in <module>
    from .codegen import PyCodegen
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/codegen.py", line 43, in <module>
    from .variables.functions import (
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/variables/functions.py", line 71, in <module>
    from torch.distributed.fsdp._fully_shard import _fsdp_param_group
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/fsdp/__init__.py", line 1, in <module>
    from ._flat_param import FlatParameter as FlatParameter
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/fsdp/_flat_param.py", line 33, in <module>
    from ._fsdp_extensions import (
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/fsdp/_fsdp_extensions.py", line 8, in <module>
    from torch.distributed.fsdp._shard_utils import (
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/fsdp/_shard_utils.py", line 18, in <module>
    from torch.distributed.tensor import DeviceMesh, DTensor, Replicate, Shard as DShard
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/tensor/__init__.py", line 4, in <module>
    import torch.distributed.tensor._ops  # force import all built-in dtensor ops
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/tensor/_ops/__init__.py", line 2, in <module>
    from ._conv_ops import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/tensor/_ops/_conv_ops.py", line 5, in <module>
    from torch.distributed.tensor._dtensor_spec import DTensorSpec, TensorMeta
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/tensor/_dtensor_spec.py", line 6, in <module>
    from torch.distributed.tensor.placement_types import (
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/tensor/placement_types.py", line 10, in <module>
    from torch.distributed.tensor._collective_utils import (
  File "/home/yohei/dt-inductor/pytorch/torch/distributed/tensor/_collective_utils.py", line 29, in <module>
    @torch.library.register_fake("_dtensor::shard_dim_alltoall")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/library.py", line 1023, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/home/yohei/dt-inductor/pytorch/torch/library.py", line 193, in _register_fake
    source = torch._library.utils.get_source(_stacklevel + 1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_library/utils.py", line 54, in get_source
    frame = inspect.getframeinfo(sys._getframe(stacklevel))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/inspect.py", line 1718, in getframeinfo
    lines, lnum = findsource(frame)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/inspect.py", line 1090, in findsource
    module = getmodule(object, file)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/inspect.py", line 1007, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/torch-spyre/torch_spyre/__init__.py", line 136, in __getattr__
    if hasattr(impl, name):
       ^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/torch-spyre/torch_spyre/__init__.py", line 47, in __getattr__
    self._lazy_init()
  File "/home/yohei/dt-inductor/torch-spyre/torch_spyre/__init__.py", line 70, in _lazy_init
    ts_autoload()
  File "/home/yohei/dt-inductor/torch-spyre/torch_spyre/_inductor/__init__.py", line 40, in _autoload
    from .dsc import SuperDSCScheduling
  File "/home/yohei/dt-inductor/torch-spyre/torch_spyre/_inductor/dsc.py", line 18, in <module>
    from torch._inductor.codegen.simd import SIMDScheduling
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/codegen/simd.py", line 32, in <module>
    from .. import config, ir, scheduler
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/ir.py", line 38, in <module>
    from torch._export.serde.serialize import GraphModuleSerializer
  File "/home/yohei/dt-inductor/pytorch/torch/_export/serde/serialize.py", line 37, in <module>
    from torch._export.non_strict_utils import _enable_graph_inputs_of_type_nn_module
  File "/home/yohei/dt-inductor/pytorch/torch/_export/non_strict_utils.py", line 17, in <module>
    from torch._dynamo.variables.builder import TrackedFake
ImportError: cannot import name 'TrackedFake' from partially initialized module 'torch._dynamo.variables.builder' (most likely due to a circular import) (/home/yohei/dt-inductor/pytorch/torch/_dynamo/variables/builder.py)
```

**Comment by yoheiueda** [comment]
@thoangtrvn  Could you help me understand what’s going wrong?

**Comment by thoangtrvn** [comment]
@yoheiueda : Thank you! I just raise a PR to address this.
