### ISSUE TITLE
torch.ne and other comparison operators return float, causing compilation error

### ISSUE THREAD

**Issue by yoheiueda** [torch-spyre/torch-spyre#227]
### What happened?

On Spyre, comparison operators such as torch.ne return float tensor, while on CPU they return a boolean tensor. This difference allowed the following code to work on Spyre without explicit type conversion before PR #201:

```
import torch
import torch.nn as nn

class test(nn.Module):
    def forward(self, input1, input2, input3):
        tmp = torch.ne(input1, input2)
        # tmp = tmp.to(dtype=torch.float16)
        return torch.matmul(tmp, input3)

input1_cpu = torch.ones(64, 64, dtype=torch.float16)
input2_cpu = torch.zeros(64, 64, dtype=torch.float16)
input3_cpu = torch.ones(64, 64, dtype=torch.float16)

input1_spyre = input1_cpu.to("spyre")
input2_spyre = input2_cpu.to("spyre")
input3_spyre = input3_cpu.to("spyre")

net = test().to("spyre")
net_compile = torch.compile(net, backend="inductor")
output_spyre = net_compile(input1_spyre, input2_spyre, input3_spyre)
output_cpu = output_spyre.cpu()

print(f"Spyre result\n{output_cpu}")
```

After PR #201 was merged, the above code fails with:
```
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/pattern_matcher.py", line 1339, in check_fn
    args[i] = torch.empty_strided(
              ^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
```

I suspect this issue is related to the fake op change introduced in PR #201. Before that PR, Spyre used a Spyre-specific fake op for torch.ne that didn’t enforce dtype checks. After PR #201, Spyre switched to a generic fake op, which correctly validates the dtype. This is just my guess and hasn’t been confirmed yet.

I don't think this is a regression in PR #201; rather, it exposed that Spyre does not support to(dtype=...).

When I uncomment the tmp.to(dtype=torch.float16) line, I get:
```
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/ops_handler.py", line 132, in to_dtype
    raise NotImplementedError
torch._inductor.exc.InductorError: NotImplementedError:
```

This suggests Spyre’s `to_dtype` handler is unimplemented. For this case, `to(dtype=...)` can be a no-op.

### What did you expect to happen?

`to(dtype=...)` works for the result of comparison operators like torch.ne on Spyre.

### How can we reproduce it?

Run the above code on Spyre.

### Any environmental details we need to know?

I am using 19f4bafcbea6baddd880f815e8ef95a50a60da1f

### Relevant log output

```Shell
Error message for floating-point tensor error:

Traceback (most recent call last):
  File "/home/yohei/test/notequal.py", line 26, in <module>
    output_spyre = net_compile(input1_spyre, input2_spyre, input3_spyre)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/eval_frame.py", line 663, in _fn
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/output_graph.py", line 1544, in _call_user_compiler
    raise BackendCompilerFailed(
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/output_graph.py", line 1519, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/repro/after_dynamo.py", line 150, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/__init__.py", line 2347, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/compile_fx.py", line 2088, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/torch-spyre/torch_spyre/_inductor/fake_ops.py", line 49, in __call__
    return super().__call__(gm, example_inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/backends/common.py", line 101, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_functorch/aot_autograd.py", line 1168, in aot_module_simplified
    compiled_fn = AOTAutogradCache.load(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_functorch/_aot_autograd/autograd_cache.py", line 775, in load
    compiled_fn = dispatch_and_compile()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_functorch/aot_autograd.py", line 1153, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_functorch/aot_autograd.py", line 570, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_functorch/aot_autograd.py", line 820, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
                               ^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 219, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_functorch/aot_autograd.py", line 479, in __call__
    return self.compiler_fn(gm, example_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/compile_fx.py", line 1881, in fw_compiler_base
    _recursive_joint_graph_passes(gm)
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/compile_fx.py", line 367, in _recursive_joint_graph_passes
    joint_graph_passes(gm)
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/fx_passes/joint_graph.py", line 561, in joint_graph_passes
    ).apply_graph_pass(patterns.apply)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/fx/passes/graph_transform_observer.py", line 85, in apply_graph_pass
    return pass_fn(self.gm.graph)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/pattern_matcher.py", line 1870, in apply
    if is_match(m) and entry.extra_check(m):
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/pattern_matcher.py", line 1339, in check_fn
    args[i] = torch.empty_strided(
              ^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

Error message for NotImplementedError for to_dtype:
C1209 14:45:56.184000 2084131 torch/_inductor/scheduler.py:1204] [0/0] Error in codegen for ComputedBuffer(name='buf1', layout=FixedTiledLayout('spyre:0', torch.float16, size=[64, 64], stride=[64, 1], device_layout=SpyreTensorLayout(device_size=[1, 64, 64], device_strides=[4096, 64, 1], dim_map =[1, 0, 1], num_stick_dims=1, format="Dense")), data=Pointwise(device=device(type='spyre', index=0), dtype=torch.float16, inner_fn=<function make_pointwise.<locals>.inner.<locals>.inner_fn at 0x7febe51751c0>, ranges=[64, 64]))
Traceback (most recent call last):
  File "/home/yohei/test/notequal.py", line 20, in <module>
    output_spyre = net_compile(input1_spyre, input2_spyre, input3_spyre)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_dynamo/eval_frame.py", line 663, in _fn
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/compile_fx.py", line 760, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/compile_fx.py", line 745, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/compile_fx.py", line 1295, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/compile_fx.py", line 1197, in codegen_and_compile
    compiled_fn = graph.compile_to_module().call
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/graph.py", line 2083, in compile_to_module
    return self._compile_to_module()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/graph.py", line 2091, in _compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
                                                             ^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/graph.py", line 2002, in codegen
    self.scheduler.codegen()
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/scheduler.py", line 4135, in codegen
    else self._codegen(self.nodes)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/scheduler.py", line 4264, in _codegen
    self.get_backend(device).codegen_node(node)
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/codegen/simd.py", line 1320, in codegen_node
    return self.codegen_node_schedule(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/codegen/simd.py", line 1361, in codegen_node_schedule
    self.codegen_node_schedule_with_kernel(node_schedule, kernel)
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/codegen/simd.py", line 1461, in codegen_node_schedule_with_kernel
    node.codegen(index_vars)
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/scheduler.py", line 1202, in codegen
    self._body(*index_vars)
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/loop_body.py", line 407, in __call__
    result = self.root_block()
             ^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/loop_body.py", line 476, in __call__
    return InterpreterShim(graph, submodules).run(V.get_ops_handler())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/loop_body.py", line 60, in run
    return super().run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/fx/interpreter.py", line 171, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/loop_body.py", line 56, in run_node
    return super().run_node(n)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/fx/interpreter.py", line 240, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/fx/interpreter.py", line 344, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/ops_handler.py", line 781, in call_default
    return self._default(target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/ops_handler.py", line 1041, in _default
    return getattr(self._inner, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/ops_handler.py", line 781, in call_default
    return self._default(target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/codegen/common.py", line 2296, in _default
    value = getattr(self.parent_handler, name)(*args, **kwargs)  # type: ignore[has-type]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yohei/dt-inductor/pytorch/torch/_inductor/ops_handler.py", line 132, in to_dtype
    raise NotImplementedError
torch._inductor.exc.InductorError: NotImplementedError:

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
```

**Comment by dgrove-oss** [comment]
Thanks for the detailed bug report.

I think we want to approach this by adding `to_dtype` to `SpyreKernelOverrides` as is done for the triton and halide backends. We can then pass `to_dtype` through to SDSC code generation.   You are right that in this particular case, it could probably really be a noop, but in general we want to pass it down as a pointwise type conversion operation, expose the source/dst types to the SDSC code generator, and let it invoke the right data conversion ddl (or a no-op copy ddl).

**Comment by yoheiueda** [comment]
@dgrove-oss  Thanks for the explanation.

Here’s what I’m thinking: we could decompose torch.ne like this. torch.ops.spyre.ne is the current Spyre's notequal implementation that returns a float:

```
orig_ne = torch.ne

def spyre_ne(
    input: torch.Tensor, other: torch.Tensor, *, out: torch.Tensor = None
) -> torch.Tensor:
    if input.device.type == "spyre":
        tmp = torch.ops.spyre.ne(input, other)
        result = tmp.to(dtype=torch.bool)
        if out is not None:
            out.copy_(result)
        return result
    else:
        return orig_ne(input, other, out=out)

torch.ne = spyre_ne
```

Next, we would implement `torch.Tensor.to(dtype=...)` for Spyre. Initially, this could be a no-op, and later we can add proper data conversion.

With this approach, the code from the first comment would effectively translate to:

```
tmp1 = torch.ops.spyre.ne(input1, input2)
tmp2 = tmp1.to(dtype=torch.bool)
tmp3 = tmp2.to(dtype=torch.float16)
tmp4 = torch.matmul(tmp3, input3)
return tmp4
```

Ideally, redundant `to(dtype=...)` calls would be optimized away during compilation.
